### PR TITLE
Relegate slicing to is_header, remove _minctest

### PR DESCRIPTION
**Pull request by effigies**
Additional tweaks:
* Use more definitive test for MINC1 images
* Remove unused import

### CODE REVIEW

**Comment by bcipolli** [comment]
Much easier, thanks! Lemme think about the change for a bit!

**Comment by effigies** [comment]
Just as a point of process, we can avoid cluttering the final PR with merge commits if you push any changes you have, let me know you're ready to merge, and I can rebase against your branch. Then when you rebase against nibabel/master, the merge commits will disappear.

**Comment by effigies** [comment]
Not sure why the test is failing.

    import nibabel as nib
    bstr = open('nibabel/tests/data/tiny.mnc', 'rb').read(1024)
    nib.minc1.Minc1Header.is_header(bstr)

**Comment by bcipolli** [comment]
I'd made a testing exception for the `Minc1Header` softness. The test exception needs to be removed, now that you made the check more specific (which is great!)

**Comment by effigies** [comment]
I suppose I could've looked for an exception. Passing locally.

**Comment by bcipolli** [comment]
No problem. Faster to ask, and it definitely wouldn't be obvious.

**Comment by effigies** [comment]
Python 3 bug. Fixed and squashed. Passing now.

**Comment by bcipolli** [comment]
@effigies would you mind to check the other `is_header` functions to make sure all of them are permissive (accept larger binary blocks) and don't throw value errors in this case, but instead slice in the way you did for the `MincHeader`s?

**Comment by effigies** [comment]
`nibabel/analyze.py`: [`binaryblock[:klass.sizeof_hdr]`](https://github.com/bcipolli/nibabel/blob/reload/nibabel/analyze.py#L901)
`nibabel/spm2analyze.py`: [`binaryblock[:klass.sizeof_hdr]`](https://github.com/bcipolli/nibabel/blob/reload/nibabel/spm2analyze.py#L122)
`nibabel/nifti1.py`: [`binaryblock[:klass.sizeof_hdr]`](https://github.com/bcipolli/nibabel/blob/reload/nibabel/nifti1.py#L1620)
`nibabel/nifti2.py`: [`binaryblock[:klass.sizeof_hdr]`](https://github.com/bcipolli/nibabel/blob/reload/nibabel/nifti2.py#L230)

Should probably switch minc to use `klass.sizeof_hdr` instead of 4?

**Comment by bcipolli** [comment]
That'd be great, 'n rebase on the latest version of mine (if you haven't), and I think we're good!

**Comment by effigies** [comment]
All set.

**Pull request merged**
