### PR TITLE
TST: Test ValueErrors raised by is_header

### PR DESCRIPTION
**Pull request by effigies**
Might help with the reduced coverage. Also made the `unicode` -> `bytes` change I suggested. If I misunderstood I can revert it.

### CODE REVIEW

**Comment by bcipolli** [comment]
I think you understood well. I definitely oscillate on my ability to think in Python 3--thanks for catching that!

**Comment by effigies** [comment]
Don't think that will quite bring nipy/nibabel#329 up to (+0.0) coverage, but pretty close. I can look through again for untested code paths.

**Comment by bcipolli** [comment]
OK, will wait to merge until you're done.

**Comment by effigies** [comment]
I guess the deprecation warnings on `class_map`/`ext_map` haven't been tested. And `is_valid_filename` isn't called from anywhere, and isn't tested. Would you want to keep that, or drop it?

**Comment by bcipolli** [comment]
drop it pls

**Comment by bcipolli** [comment]
@effigies I added you as a collaborator to my repo. You're welcome to do PRs here, work on my branch directly and ask questions on the original branch, or whatever else could work for ya.

I don't have any time to do actual work on this today (responding to comments is no prob), but I definitely don't want to block you!

**Pull request closed without merging**
